# This yaml file creates a wordpress instance and a my sql database
# To create a network of these instances, the port, virtual host, and container names must be changed in regards
# to each instance. 
#

version: "3.3"
services:
   db:
     image: mysql:5.7
     volumes:
       - "./db_data_site1:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     container_name: wp_site1_db
   wordpress:
      depends_on:
         -  db
      image: wordpress:latest
      ports:
        - "8001:80"
      restart: always
      environment:
        VIRTUAL_HOST: site1.wordpress.cdhsc.org      
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
      container_name: wp_site1
